#ifndef STATE_MACHINE_H
#define STATE_MACHINE_H

typedef enum {
    APP_INITIALIZE,
    APP_READY,
    APP_WIFI_SCANNING,
    APP_WIFI_FOUND,
    APP_WIFI_NOT_FOUND,
    APP_BLE_SCANNING,
    APP_BLE_FOUND,
    APP_BLE_NOT_FOUND
} APP_STATE;

#endif